name: street_food_recognizer
description: A modern street food recognition app with analytics and history
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # ML
  tflite_flutter: ^0.12.0
  image: ^4.1.7
  # Media + UI
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/StreetFoodlogo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/model.tflite
    - assets/labels.txt

